### ISSUE TITLE
Translated versions of the game are broken

### ISSUE THREAD

**Issue by johnnyapol** [TornDotSpace/Torn-Issues#10]
Clicking on a translation simply does nothing and manually pasting the url in brings up a broken page where the user cannot connect.

**Comment by 2swap** [comment]
This is new, it used to work. Must be something to do with all of the changes to the way the backend is structured. There are some other issues with translations, for example messages that the server sends to the client are always in english, so is some text on the homepage, and also there are issues with accented characters rendering improperly after being pulled from the spanish.json and other language files.

**Comment by tardisfromtornspace** [comment]
I see no broken redirect...
![imagen](https://user-images.githubusercontent.com/52273174/60278061-0802e280-98ff-11e9-9c28-9f627145b62b.png)
![imagen](https://user-images.githubusercontent.com/52273174/60278140-210b9380-98ff-11e9-95df-acd25bd6a35c.png)
For me there's no broken redirect.

**Comment by tardisfromtornspace** [comment]
Or you have already fixed that, or whatever is wrong is not in the part of the game you are looking for.

**Comment by tardisfromtornspace** [comment]
Sorry if I sounded rude.

**Comment by johnnyapol** [comment]
Looks like this is firefox specific then. Interesting

**Comment by tardisfromtornspace** [comment]
I'm working in Firefox, the problem is not there

**Comment by johnnyapol** [comment]
This will be fixed in the next client deployment. Turns out the spanish files were fine but the other ones were out of sync + some workarounds added with react.
