### ISSUE TITLE
Modify player storage method

### ISSUE THREAD

**Issue by chrisj1** [TornDotSpace/Torn-Issues#16]
Currently when a player signs up a new file is created on the file system. I propose to instead change to use sqllite. This should have the following benefits:

* Reading and writing from an SQLite database is often faster than reading and writing individual files from disk. Advertised 35% faster
* The application only has to load the data it needs, rather than reading the entire file and holding a complete parse in memory.
* Easier and more robust to add player information
* Easily perform queries on all players
* Allows multiple programs to access the same database
* Easier to manually change
* Easier to compute player statistics using existing tools.

I would like to hear what other people think about this idea. I have looked at the code and it seems it could be accomplished by changing only the `save()` and` load()` functions within app.js.

**Comment by chrisj1** [comment]
Looks like the save file format is a mess. I need to talk to @2swap about sorting everything out. Looks like he is storing a lot of information that could be reduced to a simple computation. For instance, storing the amount mined and having a separate bool if it is over a certain amount.

**Comment by johnnyapol** [comment]
test

**Comment by chrisj1** [comment]
We will be using mongodb instead of sqlite.

**Comment by DamienVesper** [comment]
Very good, it's honestly not that bad.

**Comment by chrisj1** [comment]
> Very good, it's honestly not that bad.

I personally prefer sql but at this point, MongoDB is orders of magnitude faster to implement. I know Toontown uses it with 5k connections so it should work for us.

**Comment by johnnyapol** [comment]
This is currently implemented in the master branch (not production) and fingers crossed it will be apart of the next server deployment (no current ETA)
