### ISSUE TITLE
That rank 20 sprite

### ISSUE THREAD

**Issue by tardisfromtornspace** [TornDotSpace/Torn-Issues#28]
Yeah I know it was a bit too intimidating and black for an alien rank 20 but ok...
![newR15goodsize fw](https://user-images.githubusercontent.com/52273174/60291287-ef082a80-991a-11e9-8ecb-13b6606a6551.png)

**Comment by DamienVesper** [comment]
@tardisfromtornspace r21 sprite. Since the rank 21 has been achieved by the one user, he should decide what his ship looks like.

**Comment by tardisfromtornspace** [comment]
Just rank 20, I don't want an Elitist ship (no pun intended, since I really want the Elite Conqueror and Hydra finished).

**Comment by DamienVesper** [comment]
the conqueror is the rank 20 ship

**Comment by tardisfromtornspace** [comment]
The Conqueror is rank 15, Elite Conqueror is rank 20.
PD: please move this conversation to Discord.
