### ISSUE TITLE
Doesn't work well on firefox- scrolling bugs, crashes often, and quite laggy

### ISSUE THREAD

**Issue by 2swap** [TornDotSpace/Torn-Issues#3]

**Comment by elihschiff** [comment]
This is the most important bug holding back torn.space at the moment. How is this only medium priority?

**Comment by DamienVesper** [comment]
@elihschiff Chrome should be a good alternative if it crashes on Firefox. Also, there are more bugs than merely no support for one browser, such as hitting the website with a denial of service attack.

**Comment by elihschiff** [comment]
@DamienVesper that is like telling me to just use internet explorer. Chrome is a cancer slowly destroying the free internet as we know it. If anything the game should be optomize for Firefox first and chrome should be the afterthought

**Comment by tardisfromtornspace** [comment]
Agreed.

**Comment by DamienVesper** [comment]
If anything just use a working browser. Period.

**Comment by tardisfromtornspace** [comment]
Also in my computer Firefox worked far better than Chrome, at least in torn.space.

**Comment by johnnyapol** [comment]
Vast majority of the performance issues should be addressed on the next client deploy thanks to recent work done. Closing this for now, we can re-evaluate scrolling and other issues in a future ticket.
