### ISSUE TITLE
Revamp deployment system

### ISSUE THREAD

**Issue by johnnyapol** [TornDotSpace/Torn-Issues#30]
Currently the torn deployment process consists of manually building the appropriate node stuff and copying it over to the server via sftp and hoping for the best. Small hotfixes to the server code have been done on the backend without the need for a full re-deploy; however, this process can be largely automated 

On the torn git repository, we now have two branches: "master" and "torn-production". Potentially in the future we may add a "torn-beta" branch if there comes a need for a reliable beta server. Master will serve as the mainline development branch and torn-production will correspond to the currently deployed code base.

When an update to "torn-production" is pushed, a webhook or check should be generated and processed by the monitoring agent which will proceed to clone the new changes and build the server & client and deploy the update. Once #14 is done, we can even have it delay updates until nobody is online to avoid user interruptions. 

Currently this issue is blocked on https://github.com/TornDotSpace/Mira/issues/3 and complete implementation by #14 . 

This will allow us to synchronize our development efforts and also easily revert changes to the server if the need arises.

**Comment by chrisj1** [comment]
Sounds good.

**Comment by johnnyapol** [comment]
This is being worked on and will be first tested with the launch of a test server later this week.
