### ISSUE TITLE
Revamp Achievement system

### ISSUE THREAD

**Issue by chrisj1** [TornDotSpace/Torn-Issues#31]
Instead of making each achievement a boolean on the player object I propose we do the following:
Have a dictionary that maps from the name of the achievement to a function that returns if the achievement has been unlocked. This would make adding additional achievements easy and avoid needing to store extra data in the player object.

**Comment by tardisfromtornspace** [comment]
Hmmm as long as it improves performance and doesn't suffer a bug I'm ok with this.
