### ISSUE TITLE
Fix chat mute dodging / abuse

### ISSUE THREAD

**Issue by DamienVesper** [TornDotSpace/Torn-Issues#34]
Currently, the chat can be easily bypassed by (i.e.: replacing the g's with a 6 and spamming in all caps to show the N word). This package (https://www.npmjs.com/package/bad-words/) is a better one, at least, to replace the current chat filter. Please change the filter so it covers more words.

**Comment by DamienVesper** [comment]
In addition to that, private messages can be spammed without any punishment, and mutes do not apply to PMs. And even if a user IS muted, they can leave the game and rejoin, therefore being unmuted.

Also, the automute system sometimes is triggered too early, consider making the algorithm less intensive, such as requiring a bit more time (.179 of a second maybe?) before muting.

**Comment by chrisj1** [comment]
@DamienVesper We are currently using that package. No matter what people will find ways to bypass the filter.

We could try allowing user's mute to be persistent.

**Comment by chrisj1** [comment]
We also want to make sure the filter is not too prone to false positives. For instance, if they were are talking about their favorite proper subset continuously differentiable functions and when they say I love Lipschitz continuous and the chat flags that that as profanity.

**Comment by johnnyapol** [comment]
As Eigenvector said, that is currently our filter. The filter will always be an uphill battle. The chat muting stuff will need to be fixed, so that will become the topic of this issue

**Comment by johnnyapol** [comment]
This has been fixed in the current master branch and will be apart of the next deployment.
