### ISSUE TITLE
Higher Ranked Bots

### ISSUE THREAD

**Issue by DamienVesper** [TornDotSpace/Torn-Issues#38]
Currently, bots are capped at rank 13 (and seeing a rank 13 is very rare), perhaps consider adding higher ranked bots, making higher ranked bots spawn more often, or a combination of the two. The drop rate between the r12 and r13 bots is very high as well.

**Comment by tardisfromtornspace** [comment]
Make it so there are r14 and 15 bots too, but only 1 of those at the time. No Elite Bots, albeit you could make it so r15 bots could give more xp (as if they were rank 16-17).

**Comment by DamienVesper** [comment]
Was trying to hit the comment button but hit the wrong thing, sorry...Two r14's at a time, one human and one alien, and one r15 at a time, called by a Math.floor(Math.random() * 2) ?

**Comment by johnnyapol** [comment]
Done in a recent updated.
