### ISSUE TITLE
Lore backend mechanics are redundant

### ISSUE THREAD

**Issue by 2swap** [TornDotSpace/Torn-Issues#41]
The clientside can handle the lore, currently they ping the server when the homepage button is clicked

**Comment by johnnyapol** [comment]
I addressed most of this in recent patches to the source (clients won't attempt to connect to the server until a login or guest request is made). I think they should still try to connect before displaying the lore in the event of the game server being down.

**Comment by johnnyapol** [comment]
Closing this out as this is addressed in the master branch (not in production yet)
