### ISSUE TITLE
Pressing enter on the homescreen does nothing, it should log you in after you've typed your credentials

### ISSUE THREAD

**Issue by 2swap** [TornDotSpace/Torn-Issues#5]

**Comment by DamienVesper** [comment]
login btn fix and continuous crash fix 
`
<form>
	<input class = "signin-user" type = "text" maxlength = "20" minlength = "4" required />
	<input class = "signin-pass" type = "password" maxlength = "32" required />
	<input class = "signin-btn" type = "submit" value = "login" />
</form>
<script>
	//prevent page refresh
	document.querySelector(`input.signin-btn`).onclick(function(e){
		e.preventDefault(); //or something like that
		bt.emit(`login`) {
			user: document.querySelector(`input.signin-user`).value.toString().toLowerCase(),
			pass: document.querySelector(`input.signin-pass`).value.toString()
		}
	}
</script>
`

**Comment by DamienVesper** [comment]
Use a form tag (form, input[type=submit).
https://discordapp.com/channels/247490958374076416/247490958374076416/594185706126049281

**Comment by johnnyapol** [comment]
This has been fixed in our current dev branch and will be part of the next client deployment
