### ISSUE TITLE
Server often has random spikes in lag that stop the game for about 2 seconds every now and then. This is new, I don't know the cause.

### ISSUE THREAD

**Issue by 2swap** [TornDotSpace/Torn-Issues#6]

**Comment by johnnyapol** [comment]
This may have been related to the service interruptions occurring on our host. After they applied their MDS / ZombieLoad patches and rebooted the box things have been running considerably better.

**Comment by johnnyapol** [comment]
Closing this out as the server code has recently gone through a major rewrite. We will need to investigate this further after it is better tested and deployed.
