### ISSUE TITLE
There is no content filter for usernames or some messages in chat

### ISSUE THREAD

**Issue by chrisj1** [TornDotSpace/Torn-Issues#8]
Users may give themselves not family friendly names. We need a content filter to block these messages and any attempts at obfuscation.

**Comment by johnnyapol** [comment]
There also is the discussion of what we do with the accounts will have invalid names after this change. Perhaps we'll have to separate the username from the display name

**Comment by chrisj1** [comment]
Just implemented a basic chat filter and checked for profane names while registering. Pushed commit to master branch.

**Comment by chrisj1** [comment]
> There also is the discussion of what we do with the accounts will have invalid names after this change. Perhaps we'll have to separate the username from the display name

@johnnyapol I just talked to @2swap about this. He says very few users are active with profane names. We might be able to safely remove them.

**Comment by chrisj1** [comment]
We will deal with bad usernames as part of adding display names see issue #29.
